### ISSUE TITLE
Create Phoenix Endpoint to Receive SNS Notification Data

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-ses-lambda#3]
We have the Lambda function to _send_ emails working. 🎉 
Now we want to create an SNS topic so that our Lambda can receive SES related notifications.
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-sns-notifications.html

But what happens when with the information in the SNS Notification?
In the past we have stored this data in S3 or DynamoDB but both those data stores are _cumbersome_ to query and have per-request charges for saving/getting data. So we _need_ a way of getting the SNS notification info _back_ to our PostgreSQL (_main_) database.

Our ultimate objective with **`email`** is to have a real-time ***dashboard*** where we can **visualise** the **_aggregate_ deliverability stats** and **_specific_ stats** for a given person using our App (_while preserving their anonymity/privacy_). 

We still want our Lambda function to _receive_ and _process_ the SNS messages,
and then forward the formatted info back to Phoenix App via REST API endpoint.

## Todo

In order to use the _same_ tables/schema as the MVP which has detailed explanations 
see: https://github.com/dwyl/app-mvp-phoenix#schema
We are borrowing the actual migration files:

+ [x] Create `tags` table by reusing `20191113100513_create_tags.exs` migration from the MVP:
https://github.com/dwyl/app-mvp-phoenix/blob/master/priv/repo/migrations/20191113100513_create_tags.exs
+ [x] Create `status` table by reusing `20191113100912_create_status.exs` from MVP: https://github.com/dwyl/app-mvp-phoenix/blob/master/priv/repo/migrations/20191113100912_create_status.exs
+ [x] Create `people` table by reusing `20191113100920_create_people.exs` migration from the MVP:
https://github.com/dwyl/app-mvp-phoenix/blob/master/priv/repo/migrations/20191113100920_create_people.exs
+ [x] Add `person_id` to Tags using `20191113114340_add_person_id_to_tag.exs` from MVP:
https://github.com/dwyl/app-mvp-phoenix/blob/master/priv/repo/migrations/20191113114340_add_person_id_to_tag.exs
+ [x] Add `person_id` to Status using `20191113141229_add_person_id_to_status.exs` form MVP:
https://github.com/dwyl/app-mvp-phoenix/blob/master/priv/repo/migrations/20191113141229_add_person_id_to_status.exs

![image](https://user-images.githubusercontent.com/194400/74822644-5d13be80-52fd-11ea-9798-5223408e9f19.png)

This way we can run the Email and Auth Apps in several ways:
1. **both apps** use the **_same_ database** (_our preferred option during the first [100 people](https://github.com/nelsonic/nelsonic.github.io/issues/782) "Beta" phase_)
2. **`Auth`** and **`Email`** can be run _separately_ 
3. **`Email`** can be run as an _Umbrella_ App to **`Auth`**
4. We can safely _combine/merge_ all the apps into one App for simplicity.

# _Next_

+ [x] Create **`sent`** table/schema with the following fields:
  + [x] **`person_id`** (_references `person.id`_) - the person the email was sent to.
  + [x] **`template`** - the template that was used to send the email to the person.
  + [x] **`message_id`** and **`request_id`** fields to store SES metadata.
  + [x] **`status_id`** (_references `status.id`_) - the status of the email e.g: `6:sent`, `7:delivered`, `8:bounce`, etc. This allows us to have _unlimited_ statuses without tons of duplication of text. 
  > Note: the "status" does not need to be a _single_ word, it can be for example:
   "**bounce:** addressee unknown"

# _Then_

+ [x] Create `/api` endpoint that: 
  + [x] **requires** a valid JWT in order to allow data in
  + [x] ***receives*** data in a standardised form

**Comment by nelsonic** [comment]
ERD after creating the **`sent`** table:
![erd-with-sent-table](https://user-images.githubusercontent.com/194400/75200073-b6944700-575c-11ea-97c9-a7b495395a05.png)

**Comment by nelsonic** [comment]
Getting _really_ close to finishing the ingress endpoint! 
The _difficult_ part is already working! 🎉

**Comment by nelsonic** [comment]
This is now _working_ on the Heroku App!
Try it:
```
curl -v -X POST "https://phemail.herokuapp.com/api/"\
  -H "Content-Type: application/json"\
  -H "authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXNzYWdlX2lkIjoiMDEwMjAxNzA5MjAwNjc5OC1mMDQ1NjY5NC1hYzI0LTQ4N2ItOTQ2Ny1iNzliOGNlNzk4ZjItMDAwMDAwIiwic3RhdHVzIjoiQm91bmNlIFBlcm1hbmVudCIsImlhdCI6MTU4MzM0NTgyOX0.oSp0gOTcoV-YN7yk-tUtni-HHHuP58cg6AjIEJ0-tDk"
```

![image](https://user-images.githubusercontent.com/194400/75909785-a3603600-5e44-11ea-830a-8e327451e1b7.png)

**Comment by nelsonic** [comment]
Included in https://github.com/dwyl/aws-ses-lambda/pull/4 ✅
