### ISSUE TITLE
Invoke AWS Lambda Function from Elixir

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-ses-lambda#8]
There are a couple of options for invoking a Lambda function from Elixir:
+ [x] https://github.com/bbc/elixir-invoke-lambda - sadly the BBC code is tightly coupled to their infra. So it's not much _use_ to anyone `else` ... but it's a _reference_ and it's good to know they're using Elixir! 🎉 
+ [x] https://github.com/ex-aws/ex_aws_lambda

## Todo

+ [x] Setup a test Elixir project: https://github.com/dwyl/elixir-invoke-lambda-example
+ [x] attempt to invoke the AWS SES Lambda function
  + [x] `arn:aws:lambda:eu-west-1:110797354241:function:aws-ses-lambda-v1`

**Comment by nelsonic** [comment]
Can't say I'm happy about this ***failing*** build on **`master**: https://github.com/ex-aws/ex_aws
![ex_aws-build-failing](https://user-images.githubusercontent.com/194400/74363615-cefe7c00-4dc2-11ea-87ce-4e7575a0c36f.png)

https://travis-ci.org/ex-aws/ex_aws/jobs/625307766#L863
![ex_aws-build-failing-master](https://user-images.githubusercontent.com/194400/74363781-2d2b5f00-4dc3-11ea-9963-c75dc2b739c3.png)

It's only _one_ test failing ...  but `master` has been "broken" for 2 months ... 😕 
![image](https://user-images.githubusercontent.com/194400/74363764-23a1f700-4dc3-11ea-84ec-c988ee20e570.png)

Gonna keep going with this but I will be annoyed if it doesn't work ... 👨‍💻

**Comment by nelsonic** [comment]
I'm also _really_ uninspired by the non-existence of tests: [/test/lib/lambda_test.exs#L1-L14](https://github.com/ex-aws/ex_aws_lambda/blob/c8830f728c7c3ee48b09b07fe1fde62360c2df1a/test/lib/lambda_test.exs#L1-L14)
![image](https://user-images.githubusercontent.com/194400/74366745-7c27c300-4dc8-11ea-8495-cd15f9376f30.png)

I _really_ don't want to use (_rely on_) this package ... but I _really **really**_ don't want to have to _re-write_ it!!

**Comment by nelsonic** [comment]
See: https://github.com/dwyl/elixir-invoke-lambda-example#7-conclusion ✅
